services:
  gocar-next:
    container_name: gocar-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/gocar-next
    working_dir: /usr/src/gocar-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# gocar-next:   localhost:4000 <=> container:3000

